export enum EventType {
  INITIAL_PURCHASE = 'INITIAL_PURCHASE',
  RENEWAL = 'RENEWAL',
  CANCELLATION = 'CANCELLATION',
  EXPIRATION = 'EXPIRATION',
  REFUND = 'REFUND',
  UPGRADE = 'UPGRADE',
  DOWNGRADE = 'DOWNGRADE',
} 